### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by hyandell** [stephaneworkspace/astro_compute_swisseph#1]
Hi there.

I just wanted to note that the project says it is under a CC license, but it does not say which CC license it is under.

**Comment by stephaneworkspace** [comment]
Hi

this (cc by) :

This license lets others distribute, remix, adapt, and build upon your work, even commercially, as long as they credit you for the original creation. This is the most accommodating of licenses offered. Recommended for maximum dissemination and use of licensed materials.

**Comment by stephaneworkspace** [comment]
After reading more in deep the license, the CC is a mistake

License => If the developer choses the GNU GPL software license, he or she must fulfill the conditions of that license, which includes the obligation to place his or her whole software project under the GNU GPL or a compatible license. See http://www.gnu.org/licenses/old-licenses/gpl-2.0.html

**Comment by hyandell** [comment]
Thank you. Resolving.
